### ISSUE TITLE
error on raspberry pi b

### ISSUE THREAD

**Issue by fishkingsin** [resin-io/text2speech#1]
error when run the application on `Raspberry Pi B`
07.04.15 13:11:23 [+0800] Downloading application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:34:49 [+0800] Downloading application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:34:56 [+0800] Downloading application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:39:55 [+0800] Downloaded application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:39:56 [+0800] Installing application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:39:57 [+0800] Installed application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:39:57 [+0800] Starting application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:40:00 [+0800] Started application 'registry.resin.io/hellopi/43a1c8ce9a6b8b1babdc59f1d5367adfac1bf3d6'
07.04.15 13:40:14 [+0800]
07.04.15 13:40:14 [+0800] > resin-text2speech@0.0.3 start /usr/src/app
07.04.15 13:40:14 [+0800] > node server.js
07.04.15 13:40:14 [+0800]
07.04.15 13:40:18 [+0800] ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
07.04.15 13:40:18 [+0800] ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
07.04.15 13:40:18 [+0800] ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
07.04.15 13:40:18 [+0800] ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
07.04.15 13:40:18 [+0800] ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
07.04.15 13:40:18 [+0800] ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
07.04.15 13:40:18 [+0800] ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
07.04.15 13:40:18 [+0800] ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default
07.04.15 13:40:18 [+0800] [../deps/mpg123/src/output/alsa.c:165] error: cannot open device default
07.04.15 13:40:18 [+0800]
07.04.15 13:40:18 [+0800] events.js:72
07.04.15 13:40:18 [+0800] throw er; // Unhandled 'error' event
07.04.15 13:40:18 [+0800] ^
07.04.15 13:40:18 [+0800] Error: open() failed: -1
07.04.15 13:40:18 [+0800] at Speaker._open (/usr/src/app/node_modules/speaker/index.js:106:11)
07.04.15 13:40:18 [+0800] at Speaker._write (/usr/src/app/node_modules/speaker/index.js:182:21)
07.04.15 13:40:18 [+0800] at doWrite (_stream_writable.js:221:10)
07.04.15 13:40:18 [+0800] at writeOrBuffer (_stream_writable.js:211:5)
07.04.15 13:40:18 [+0800] at Speaker.Writable.write (_stream_writable.js:180:11)
07.04.15 13:40:18 [+0800] at write (_stream_readable.js:583:24)
07.04.15 13:40:18 [+0800] at flow (_stream_readable.js:592:7)
07.04.15 13:40:18 [+0800] at Decoder.pipeOnReadable (_stream_readable.js:624:5)
07.04.15 13:40:18 [+0800] at Decoder.EventEmitter.emit (events.js:92:17)
07.04.15 13:40:18 [+0800] at emitReadable_ (_stream_readable.js:408:10)
07.04.15 13:40:18 [+0800]
07.04.15 13:40:19 [+0800] npm ERR! Linux 3.18.5
07.04.15 13:40:19 [+0800] npm ERR! argv "node" "/usr/local/bin/npm" "start"
07.04.15 13:40:19 [+0800] npm ERR! node v0.10.22
07.04.15 13:40:19 [+0800] npm ERR! npm v2.5.0
07.04.15 13:40:19 [+0800] npm ERR! code ELIFECYCLE
07.04.15 13:40:19 [+0800] npm ERR! resin-text2speech@0.0.3 start: `node server.js`
07.04.15 13:40:19 [+0800] npm ERR! Exit status 8
07.04.15 13:40:19 [+0800] npm ERR!
07.04.15 13:40:19 [+0800] npm ERR! Failed at the resin-text2speech@0.0.3 start script 'node server.js'.
07.04.15 13:40:19 [+0800] npm ERR! This is most likely a problem with the resin-text2speech package,
07.04.15 13:40:19 [+0800] npm ERR! not with npm itself.
07.04.15 13:40:19 [+0800] npm ERR! Tell the author that this fails on your system:
07.04.15 13:40:19 [+0800] npm ERR! node server.js
07.04.15 13:40:19 [+0800] npm ERR! You can get their info via:
07.04.15 13:40:19 [+0800] npm ERR! npm owner ls resin-text2speech
07.04.15 13:40:19 [+0800] npm ERR! There is likely additional logging output above.
07.04.15 13:40:19 [+0800]
07.04.15 13:40:19 [+0800] npm ERR! Please include the following file with any support request:
07.04.15 13:40:19 [+0800] npm ERR! /usr/src/app/npm-debug.log
07.04.15 13:40:19 [+0800]`

**Comment by fishkingsin** [comment]
here is build log
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 988 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
Step 0 : FROM resin/rpi-node:0.10.22
 ---> be5ba2e1d687
Step 1 : RUN mkdir -p /usr/src/app && ln -s /usr/src/app /app
 ---> Using cache
 ---> beec3d2c4771
Step 2 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 20fc7dc54fc0
Step 3 : COPY . /usr/src/app
 ---> 0752068e57d6
Removing intermediate container 951f3af37ac9
Step 4 : RUN JOBS=MAX npm install --unsafe-perm
 ---> Running in 2a3d49ba43cc

> resin-text2speech@0.0.3 preinstall /usr/src/app
> bash deps.sh

Get:1 http://archive.raspbian.org jessie InRelease [14.9 kB]
Get:2 http://archive.raspbian.org jessie/main armhf Packages [12.5 MB]
Get:3 http://archive.raspbian.org jessie/contrib armhf Packages [42.5 kB]
Get:4 http://archive.raspbian.org jessie/non-free armhf Packages [83.5 kB]
Get:5 http://archive.raspbian.org jessie/rpi armhf Packages [511 B]
Get:6 http://archive.raspbian.org jessie/firmware armhf Packages [1176 B]
Fetched 12.6 MB in 15s (823 kB/s)
Reading package lists...
       Still working..
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libasound2 libasound2-data libfribidi0 libnewt0.52 libpopt0 libsamplerate0
  whiptail
Suggested packages:
  libasound2-plugins libasound2-doc
The following NEW packages will be installed:
  alsa-utils libasound2 libasound2-data libasound2-dev libfribidi0 libnewt0.52
  libpopt0 libsamplerate0 whiptail
0 upgraded, 9 newly installed, 0 to remove and 115 not upgraded.
Need to get 2565 kB of archives.
After this operation, 5475 kB of additional disk space will be used.
Get:1 http://archive.raspbian.org/raspbian/ jessie/main libnewt0.52 armhf 0.52.17-1 [64.5 kB]
Get:2 http://archive.raspbian.org/raspbian/ jessie/main libpopt0 armhf 1.16-10 [46.2 kB]
Get:3 http://archive.raspbian.org/raspbian/ jessie/main libasound2-data all 1.0.28-1 [64.8 kB]
Get:4 http://archive.raspbian.org/raspbian/ jessie/main libasound2 armhf 1.0.28-1 [316 kB]
Get:5 http://archive.raspbian.org/raspbian/ jessie/main libfribidi0 armhf 0.19.6-3 [43.2 kB]
Get:6 http://archive.raspbian.org/raspbian/ jessie/main libsamplerate0 armhf 0.1.8-8 [939 kB]
Get:7 http://archive.raspbian.org/raspbian/ jessie/main whiptail armhf 0.52.17-1 [35.8 kB]
Get:8 http://archive.raspbian.org/raspbian/ jessie/main alsa-utils armhf 1.0.28-1 [960 kB]
Get:9 http://archive.raspbian.org/raspbian/ jessie/main libasound2-dev armhf 1.0.28-1 [94.9 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2565 kB in 2s (869 kB/s)
Selecting previously unselected package libnewt0.52:armhf.
remote: (Reading database ... 27804 files and directories currently installed.)
Preparing to unpack .../libnewt0.52_0.52.17-1_armhf.deb ...
Unpacking libnewt0.52:armhf (0.52.17-1) ...
Selecting previously unselected package libpopt0:armhf.
Preparing to unpack .../libpopt0_1.16-10_armhf.deb ...
Unpacking libpopt0:armhf (1.16-10) ...
Selecting previously unselected package libasound2-data.
Preparing to unpack .../libasound2-data_1.0.28-1_all.deb ...
Unpacking libasound2-data (1.0.28-1) ...
Selecting previously unselected package libasound2:armhf.
Preparing to unpack .../libasound2_1.0.28-1_armhf.deb ...
Unpacking libasound2:armhf (1.0.28-1) ...
Selecting previously unselected package libfribidi0:armhf.
Preparing to unpack .../libfribidi0_0.19.6-3_armhf.deb ...
Unpacking libfribidi0:armhf (0.19.6-3) ...
Selecting previously unselected package libsamplerate0:armhf.
Preparing to unpack .../libsamplerate0_0.1.8-8_armhf.deb ...
Unpacking libsamplerate0:armhf (0.1.8-8) ...
Selecting previously unselected package whiptail.
Preparing to unpack .../whiptail_0.52.17-1_armhf.deb ...
Unpacking whiptail (0.52.17-1) ...
Selecting previously unselected package alsa-utils.
Preparing to unpack .../alsa-utils_1.0.28-1_armhf.deb ...
Unpacking alsa-utils (1.0.28-1) ...
Selecting previously unselected package libasound2-dev:armhf.
Preparing to unpack .../libasound2-dev_1.0.28-1_armhf.deb ...
Unpacking libasound2-dev:armhf (1.0.28-1) ...
Setting up libnewt0.52:armhf (0.52.17-1) ...
Setting up libpopt0:armhf (1.16-10) ...
Setting up libasound2-data (1.0.28-1) ...
Setting up libasound2:armhf (1.0.28-1) ...
Setting up libfribidi0:armhf (0.19.6-3) ...
Setting up libsamplerate0:armhf (0.1.8-8) ...
Setting up whiptail (0.52.17-1) ...
Setting up alsa-utils (1.0.28-1) ...
Setting up libasound2-dev:armhf (1.0.28-1) ...
Processing triggers for libc-bin (2.19-13) ...
       Still working..

> speaker@0.0.10 install /usr/src/app/node_modules/speaker
> node-gyp rebuild

```
   Still working..
   Still working..
```

make: Entering directory '/usr/src/app/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c: In function 'rates_match':
../deps/mpg123/src/output/alsa.c:53:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  return actual \* 100 > desired \* (100 - AUDIO_RATE_TOLERANCE) &&
                      ^
../deps/mpg123/src/output/alsa.c:54:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         actual \* 100 < desired \* (100 + AUDIO_RATE_TOLERANCE);
                      ^
../deps/mpg123/src/output/alsa.c: In function 'initialize_device':
../deps/mpg123/src/output/alsa.c:78:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < NUM_FORMATS; ++i) {
                ^
../deps/mpg123/src/output/alsa.c: In function 'get_formats_alsa':
../deps/mpg123/src/output/alsa.c:201:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (i = 0; i < NUM_FORMATS; ++i) {
                ^
  AR(target) Release/obj.target/deps/mpg123/liboutput.a
  COPY Release/liboutput.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
  COPY Release/binding.node
make: Leaving directory '/usr/src/app/node_modules/speaker/build'

> lame@1.0.3 install /usr/src/app/node_modules/lame
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/lame/build'
deps/mpg123/test.target.mk:112: warning: overriding recipe for target 'Release/test'
deps/lame/test.target.mk:120: warning: ignoring old recipe for target 'Release/test'
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/VbrTag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/bitstream.o
../deps/lame/libmp3lame/bitstream.c: In function 'do_gain_analysis':
../deps/lame/libmp3lame/bitstream.c:992:24: warning: unused variable 'rov' [-Wunused-variable]
     RpgResult_t _const rov = &gfc->ov_rpg;
                        ^
../deps/lame/libmp3lame/bitstream.c:991:32: warning: unused variable 'rsv' [-Wunused-variable]
     RpgStateVar_t const *const rsv = &gfc->sv_rpg;
                                ^
../deps/lame/libmp3lame/bitstream.c:990:34: warning: unused variable 'cfg' [-Wunused-variable]
     SessionConfig_t const *const cfg = &gfc->cfg;
                                  ^
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/encoder.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/fft.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/gain_analysis.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/id3tag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/lame.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/newmdct.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/presets.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
../deps/lame/libmp3lame/quantize.c: In function 'VBR_new_iteration_loop':
../deps/lame/libmp3lame/quantize.c:1734:28: warning: variable 'fullframebits' set but not used [-Wunused-but-set-variable]
         int     mean_bits, fullframebits;
                            ^
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/compat.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/parse.o
../deps/mpg123/src/libmpg123/parse.c: In function 'handle_id3v2':
../deps/mpg123/src/libmpg123/parse.c:1013:31: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
  else debug("no useful ID3v2");
                               ^
../deps/mpg123/src/libmpg123/parse.c: In function 'skip_junk':
../deps/mpg123/src/libmpg123/parse.c:1081:71: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
  else debug1("hopefully found one at %"OFF_P, (off_p)fr->rd->tell(fr));
                                                                       ^
../deps/mpg123/src/libmpg123/parse.c: In function 'wetwork':
../deps/mpg123/src/libmpg123/parse.c:1149:114: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
    if(VERBOSE3) debug3("resync try %li at %"OFF_P", got newhead 0x%08lx", try, (off_p)fr->rd->tell(fr),  newhead);
                                                                                                                  ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/frame.o
../deps/mpg123/src/libmpg123/frame.c: In function 'INT123_frame_outbuffer':
../deps/mpg123/src/libmpg123/frame.c:184:4: warning: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'size_t' [-Wformat=]
    if(NOQUIET) error2("have external buffer of size %"SIZE_P", need %"SIZE_P, (size_p)fr->buffer.size, size);
    ^
../deps/mpg123/src/libmpg123/frame.c: In function 'INT123_frame_buffers':
../deps/mpg123/src/libmpg123/frame.c:285:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(2_2_0x110_sizeof(real) > buffssize)
                            ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/format.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/equalizer.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/id3.o
../deps/mpg123/src/libmpg123/id3.c: In function 'INT123_parse_new_id3':
../deps/mpg123/src/libmpg123/id3.c:576:3: warning: right-hand operand of comma expression has no effect [-Wunused-value]
   ,1 \
   ^
../deps/mpg123/src/libmpg123/id3.c:661:35: note: in expansion of macro 'threebytes_to_long'
        if(fr->id3v2.version == 2) threebytes_to_long(tagdata+pos, framesize);
                                   ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/optimize.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/readers.o
../deps/mpg123/src/libmpg123/readers.c: In function 'plain_read':
../deps/mpg123/src/libmpg123/readers.c:60:70: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
  if(VERBOSE3) debug2("read %li bytes of %li", (long)ret, (long)count);
                                                                      ^
../deps/mpg123/src/libmpg123/readers.c: In function 'bc_add':
../deps/mpg123/src/libmpg123/readers.c:630:93: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
  if(size >=4) debug4("first bytes: %02x %02x %02x %02x", data[0], data[1], data[2], data[3]);
                                                                                             ^
../deps/mpg123/src/libmpg123/readers.c: In function 'bc_forget':
../deps/mpg123/src/libmpg123/readers.c:728:42: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
  else debug("forget with nothing there!");
                                          ^
../deps/mpg123/src/libmpg123/readers.c: In function 'INT123_feed_more':
../deps/mpg123/src/libmpg123/readers.c:763:33: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
  if(VERBOSE3) debug("feed_more");
                                 ^
../deps/mpg123/src/libmpg123/readers.c:772:82: warning: suggest braces around empty body in an 'if' statement [-Wempty-body](unsigned long)fr->rdat.buffer.last->size, (unsigned long)fr->rdat.buffer.size);
                                                                                  ^
../deps/mpg123/src/libmpg123/readers.c: In function 'buffered_fullread':
../deps/mpg123/src/libmpg123/readers.c:848:97: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
    if(VERBOSE3) debug1("buffered_fullread: buffering %li bytes from stream (if > 0)", (long)got);
                                                                                                 ^
../deps/mpg123/src/libmpg123/readers.c:856:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if(got < sizeof(readbuf)) /\* That naturally catches got == 0, too. _/
           ^
../deps/mpg123/src/libmpg123/readers.c:867:73: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
  if(VERBOSE3) debug2("wanted %li, got %li", (long)count, (long)gotcount);
                                                                         ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/tabinit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/libmpg123.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/index.o
../deps/mpg123/src/libmpg123/libmpg123.c: In function 'mpg123_plain_strerror':
../deps/mpg123/src/libmpg123/libmpg123.c:1581:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(errcode >= 0 && errcode < sizeof(mpg123_error)/sizeof(char_))
                             ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/stringbuf.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy2utf8.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/ntom.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_8bit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer1.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer2.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer3.o
../deps/mpg123/src/libmpg123/layer3.c: In function 'III_dequantize_sample':
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:804:6: note: in expansion of macro 'REFRESH_MASK'
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:818:6: note: in expansion of macro 'REFRESH_MASK'
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:842:6: note: in expansion of macro 'REFRESH_MASK'
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:890:4: note: in expansion of macro 'REFRESH_MASK'
    REFRESH_MASK;
    ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1021:6: note: in expansion of macro 'REFRESH_MASK'
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1036:6: note: in expansion of macro 'REFRESH_MASK'
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1059:6: note: in expansion of macro 'REFRESH_MASK'
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1088:4: note: in expansion of macro 'REFRESH_MASK'
    REFRESH_MASK;
    ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_arm.o
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  AR(target) Release/obj.target/deps/lame/libmp3lame.a
  AR(target) Release/obj.target/deps/lame/liblamevectorroutines.a
  COPY Release/libmp3lame.a
  COPY Release/liblamevectorroutines.a
  AR(target) Release/obj.target/deps/mpg123/libmpg123.a
  COPY Release/libmpg123.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
  CXX(target) Release/obj.target/bindings/src/node_lame.o
  CXX(target) Release/obj.target/bindings/src/node_mpg123.o
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  SOLINK_MODULE(target) Release/obj.target/bindings.node: Finished
  COPY Release/bindings.node
make: Leaving directory '/usr/src/app/node_modules/lame/build'
http@0.0.0 node_modules/http

fs@0.0.2 node_modules/fs

path@0.11.14 node_modules/path

url@0.10.3 node_modules/url
├── punycode@1.3.2
└── querystring@0.2.0

request@2.22.0 node_modules/request
├── json-stringify-safe@4.0.0
├── aws-sign@0.3.0
├── forever-agent@0.5.2
├── qs@0.6.6
├── tunnel-agent@0.3.0
├── oauth-sign@0.3.0
├── cookie-jar@0.3.0
├── mime@1.2.11
├── node-uuid@1.4.3
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── form-data@0.0.8 (async@0.2.10, combined-stream@0.0.7)
└── hawk@0.13.1 (cryptiles@0.2.2, hoek@0.8.5, sntp@0.2.4, boom@0.4.2)

speaker@0.0.10 node_modules/speaker
├── bindings@1.2.1
├── debug@2.1.3 (ms@0.7.0)
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

lame@1.0.3 node_modules/lame
├── bindings@1.2.1
├── debug@2.1.3 (ms@0.7.0)
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
 ---> ce17eab75a61
Removing intermediate container 2a3d49ba43cc
Step 5 : CMD npm start
 ---> Running in b799b6040e9e
 ---> bd07453e9bfe
Removing intermediate container b799b6040e9e
Successfully built bd07453e9bfe

-----> Image created successfully!
-----> Uploading image..
       Image uploaded successfully!
Build took 7:54                            \
                             \
                              \
                               \
                                >\/7
                            _.-(6'  \
                           (=___._/`\
                                )  \ |
                               /   / |
                              /    > /
                             j    < _\
                         _.-' :``.
                         \ r=._\        `.
                        <`\_  \         .`-.
                         \ r-7`-. ._  ' .  `\
                          \`,      `-.`7  7)   )
                           \/         |  \'  / `-._
                                      ||    .'
                                       \  (
                                        >\  >
                                    ,.-' >.'
                                   <.'_.''
                                     <'

To git@git.resin.io:fishkingsin/hellopi.git
   43a1c8c..d2187f9  master -> master

**Comment by Page-** [comment]
Hey, sorry for the late response, this is working with the latest versions of this repo and of the resin image
